// @routes-hash d90ad516e157e12db806cb7d8844135c
import { Express } from "express";

import route1 from "./routes/ai/qwen060Install";
import route2 from "./routes/assets/addAssets";
import route3 from "./routes/assets/delAssets";
import route4 from "./routes/assets/delAssetsImage";
import route5 from "./routes/assets/generateAssets";
import route6 from "./routes/assets/getAssets";
import route7 from "./routes/assets/getImage";
import route8 from "./routes/assets/getStoryboard";
import route9 from "./routes/assets/polishPrompt";
import route10 from "./routes/assets/saveAssets";
import route11 from "./routes/assets/updateAssets";
import route12 from "./routes/game/addMessage";
import route13 from "./routes/game/alignSession";
import route14 from "./routes/game/applyOrchestrateOption";
import route15 from "./routes/game/commitNarrativeTurn";
import route16 from "./routes/game/continueSession";
import route17 from "./routes/game/convertAvatarVideoToGif";
import route18 from "./routes/game/copyWorld";
import route19 from "./routes/game/debugRuntimeShared";
import route20 from "./routes/game/debugStep";
import route21 from "./routes/game/deleteChapter";
import route22 from "./routes/game/deleteMessage";
import route23 from "./routes/game/deleteSession";
import route24 from "./routes/game/deleteWorld";
import route25 from "./routes/game/deleteWorldBookEntry";
import route26 from "./routes/game/generateImage";
import route27 from "./routes/game/getChapter";
import route28 from "./routes/game/getMessage";
import route29 from "./routes/game/getOrchestrateOptions";
import route30 from "./routes/game/getPlayTips";
import route31 from "./routes/game/getSession";
import route32 from "./routes/game/getTask";
import route33 from "./routes/game/getTrigger";
import route34 from "./routes/game/getWorld";
import route35 from "./routes/game/getWorldClock";
import route36 from "./routes/game/importWorldBook";
import route37 from "./routes/game/importWorldRole";
import route38 from "./routes/game/initChapter";
import route39 from "./routes/game/initDebug";
import route40 from "./routes/game/initStory";
import route41 from "./routes/game/introduction";
import route42 from "./routes/game/listImportableRoles";
import route43 from "./routes/game/listSession";
import route44 from "./routes/game/listWorldBook";
import route45 from "./routes/game/listWorlds";
import route46 from "./routes/game/orchestration/index";
import route47 from "./routes/game/orchestration/minigame";
import route48 from "./routes/game/orchestrationResponseShared";
import route49 from "./routes/game/previewRuntimeOutline";
import route50 from "./routes/game/revisitMessage";
import route51 from "./routes/game/saveChapter";
import route52 from "./routes/game/saveTask";
import route53 from "./routes/game/saveTrigger";
import route54 from "./routes/game/saveWorld";
import route55 from "./routes/game/saveWorldBookEntry";
import route56 from "./routes/game/separateRoleAvatar";
import route57 from "./routes/game/startSession";
import route58 from "./routes/game/storyInfo";
import route59 from "./routes/game/streamIntroduction";
import route60 from "./routes/game/streamlines";
import route61 from "./routes/game/streamvoice";
import route62 from "./routes/game/updateWorldClockMode";
import route63 from "./routes/game/uploadImage";
import route64 from "./routes/index/index";
import route65 from "./routes/novel/addNovel";
import route66 from "./routes/novel/delNovel";
import route67 from "./routes/novel/getNovel";
import route68 from "./routes/novel/updateNovel";
import route69 from "./routes/other/clearDatabase";
import route70 from "./routes/other/deleteAllData";
import route71 from "./routes/other/describeImage";
import route72 from "./routes/other/getCaptcha";
import route73 from "./routes/other/login";
import route74 from "./routes/other/register";
import route75 from "./routes/other/testAI";
import route76 from "./routes/other/testImage";
import route77 from "./routes/other/testVideo";
import route78 from "./routes/other/testVoiceClone";
import route79 from "./routes/other/testVoiceDesign";
import route80 from "./routes/outline/addOutline";
import route81 from "./routes/outline/agentsOutline";
import route82 from "./routes/outline/delOutline";
import route83 from "./routes/outline/getHistory";
import route84 from "./routes/outline/getOutline";
import route85 from "./routes/outline/getPartScript";
import route86 from "./routes/outline/getStoryline";
import route87 from "./routes/outline/setHistory";
import route88 from "./routes/outline/updateOutline";
import route89 from "./routes/outline/updateScript";
import route90 from "./routes/outline/updateStoryline";
import route91 from "./routes/project/addProject";
import route92 from "./routes/project/delProject";
import route93 from "./routes/project/getProject";
import route94 from "./routes/project/getProjectCount";
import route95 from "./routes/project/getSingleProject";
import route96 from "./routes/project/updateProject";
import route97 from "./routes/prompt/getPrompts";
import route98 from "./routes/prompt/updatePrompt";
import route99 from "./routes/script/deleteScriptSegment";
import route100 from "./routes/script/generateScriptApi";
import route101 from "./routes/script/generateScriptSave";
import route102 from "./routes/script/generateScriptSegments";
import route103 from "./routes/script/geScriptApi";
import route104 from "./routes/script/getScriptSegments";
import route105 from "./routes/script/updateScriptSegment";
import route106 from "./routes/setting/addModel";
import route107 from "./routes/setting/configurationModel";
import route108 from "./routes/setting/deleteChatHistory";
import route109 from "./routes/setting/delModel";
import route110 from "./routes/setting/getAiModelList";
import route111 from "./routes/setting/getAiModelMap";
import route112 from "./routes/setting/getAiTokenUsageLog";
import route113 from "./routes/setting/getAiTokenUsageStats";
import route114 from "./routes/setting/getChatHistoryDetail";
import route115 from "./routes/setting/getChatHistoryList";
import route116 from "./routes/setting/getLog";
import route117 from "./routes/setting/getSetting";
import route118 from "./routes/setting/getVideoModelDetail";
import route119 from "./routes/setting/getVideoModelList";
import route120 from "./routes/setting/getVoiceModelList";
import route121 from "./routes/setting/localAvatarMatting";
import route122 from "./routes/setting/saveStoryRuntimeConfig";
import route123 from "./routes/setting/updateModel";
import route124 from "./routes/setting/updeteModel";
import route125 from "./routes/storyboard/batchSuperScoreImage";
import route126 from "./routes/storyboard/chatStoryboard";
import route127 from "./routes/storyboard/delStoryboard";
import route128 from "./routes/storyboard/generateShotImage";
import route129 from "./routes/storyboard/generateStoryboardApi";
import route130 from "./routes/storyboard/generateVideoPrompt";
import route131 from "./routes/storyboard/getStoryboard";
import route132 from "./routes/storyboard/keepStoryboard";
import route133 from "./routes/storyboard/saveStoryboard";
import route134 from "./routes/storyboard/uploadImage";
import route135 from "./routes/task/getTaskApi";
import route136 from "./routes/task/taskDetails";
import route137 from "./routes/user/changePassword";
import route138 from "./routes/user/getUser";
import route139 from "./routes/user/saveUser";
import route140 from "./routes/video/addVideo";
import route141 from "./routes/video/addVideoConfig";
import route142 from "./routes/video/deleteVideoConfig";
import route143 from "./routes/video/generateByConfig";
import route144 from "./routes/video/generatePrompt";
import route145 from "./routes/video/generateVideo";
import route146 from "./routes/video/getManufacturer";
import route147 from "./routes/video/getVideo";
import route148 from "./routes/video/getVideoConfigs";
import route149 from "./routes/video/getVideoModel";
import route150 from "./routes/video/getVideoStoryboards";
import route151 from "./routes/video/refreshVideoStatus";
import route152 from "./routes/video/reviseVideoStoryboards";
import route153 from "./routes/video/saveVideo";
import route154 from "./routes/video/upDateVideoConfig";
import route155 from "./routes/video/uploadAudio";
import route156 from "./routes/voice/audioProxy";
import route157 from "./routes/voice/generateBindingVoice";
import route158 from "./routes/voice/getVoices";
import route159 from "./routes/voice/listAliyunPresets";
import route160 from "./routes/voice/listMiniMaxPresets";
import route161 from "./routes/voice/mossTtsInstall";
import route162 from "./routes/voice/polishPrompt";
import route163 from "./routes/voice/preview";
import route164 from "./routes/voice/transcribe";
import route165 from "./routes/voice/uploadAudio";

export default async (app: Express) => {
  app.use("/ai/qwen060Install", route1);
  app.use("/assets/addAssets", route2);
  app.use("/assets/delAssets", route3);
  app.use("/assets/delAssetsImage", route4);
  app.use("/assets/generateAssets", route5);
  app.use("/assets/getAssets", route6);
  app.use("/assets/getImage", route7);
  app.use("/assets/getStoryboard", route8);
  app.use("/assets/polishPrompt", route9);
  app.use("/assets/saveAssets", route10);
  app.use("/assets/updateAssets", route11);
  app.use("/game/addMessage", route12);
  app.use("/game/alignSession", route13);
  app.use("/game/applyOrchestrateOption", route14);
  app.use("/game/commitNarrativeTurn", route15);
  app.use("/game/continueSession", route16);
  app.use("/game/convertAvatarVideoToGif", route17);
  app.use("/game/copyWorld", route18);
  app.use("/game/debugRuntimeShared", route19);
  app.use("/game/debugStep", route20);
  app.use("/game/deleteChapter", route21);
  app.use("/game/deleteMessage", route22);
  app.use("/game/deleteSession", route23);
  app.use("/game/deleteWorld", route24);
  app.use("/game/deleteWorldBookEntry", route25);
  app.use("/game/generateImage", route26);
  app.use("/game/getChapter", route27);
  app.use("/game/getMessage", route28);
  app.use("/game/getOrchestrateOptions", route29);
  app.use("/game/getPlayTips", route30);
  app.use("/game/getSession", route31);
  app.use("/game/getTask", route32);
  app.use("/game/getTrigger", route33);
  app.use("/game/getWorld", route34);
  app.use("/game/getWorldClock", route35);
  app.use("/game/importWorldBook", route36);
  app.use("/game/importWorldRole", route37);
  app.use("/game/initChapter", route38);
  app.use("/game/initDebug", route39);
  app.use("/game/initStory", route40);
  app.use("/game/introduction", route41);
  app.use("/game/listImportableRoles", route42);
  app.use("/game/listSession", route43);
  app.use("/game/listWorldBook", route44);
  app.use("/game/listWorlds", route45);
  app.use("/game/orchestration", route46);
  app.use("/game/orchestration/minigame", route47);
  app.use("/game/orchestrationResponseShared", route48);
  app.use("/game/previewRuntimeOutline", route49);
  app.use("/game/revisitMessage", route50);
  app.use("/game/saveChapter", route51);
  app.use("/game/saveTask", route52);
  app.use("/game/saveTrigger", route53);
  app.use("/game/saveWorld", route54);
  app.use("/game/saveWorldBookEntry", route55);
  app.use("/game/separateRoleAvatar", route56);
  app.use("/game/startSession", route57);
  app.use("/game/storyInfo", route58);
  app.use("/game/streamIntroduction", route59);
  app.use("/game/streamlines", route60);
  app.use("/game/streamvoice", route61);
  app.use("/game/updateWorldClockMode", route62);
  app.use("/game/uploadImage", route63);
  app.use("/index", route64);
  app.use("/novel/addNovel", route65);
  app.use("/novel/delNovel", route66);
  app.use("/novel/getNovel", route67);
  app.use("/novel/updateNovel", route68);
  app.use("/other/clearDatabase", route69);
  app.use("/other/deleteAllData", route70);
  app.use("/other/describeImage", route71);
  app.use("/other/getCaptcha", route72);
  app.use("/other/login", route73);
  app.use("/other/register", route74);
  app.use("/other/testAI", route75);
  app.use("/other/testImage", route76);
  app.use("/other/testVideo", route77);
  app.use("/other/testVoiceClone", route78);
  app.use("/other/testVoiceDesign", route79);
  app.use("/outline/addOutline", route80);
  app.use("/outline/agentsOutline", route81);
  app.use("/outline/delOutline", route82);
  app.use("/outline/getHistory", route83);
  app.use("/outline/getOutline", route84);
  app.use("/outline/getPartScript", route85);
  app.use("/outline/getStoryline", route86);
  app.use("/outline/setHistory", route87);
  app.use("/outline/updateOutline", route88);
  app.use("/outline/updateScript", route89);
  app.use("/outline/updateStoryline", route90);
  app.use("/project/addProject", route91);
  app.use("/project/delProject", route92);
  app.use("/project/getProject", route93);
  app.use("/project/getProjectCount", route94);
  app.use("/project/getSingleProject", route95);
  app.use("/project/updateProject", route96);
  app.use("/prompt/getPrompts", route97);
  app.use("/prompt/updatePrompt", route98);
  app.use("/script/deleteScriptSegment", route99);
  app.use("/script/generateScriptApi", route100);
  app.use("/script/generateScriptSave", route101);
  app.use("/script/generateScriptSegments", route102);
  app.use("/script/geScriptApi", route103);
  app.use("/script/getScriptSegments", route104);
  app.use("/script/updateScriptSegment", route105);
  app.use("/setting/addModel", route106);
  app.use("/setting/configurationModel", route107);
  app.use("/setting/deleteChatHistory", route108);
  app.use("/setting/delModel", route109);
  app.use("/setting/getAiModelList", route110);
  app.use("/setting/getAiModelMap", route111);
  app.use("/setting/getAiTokenUsageLog", route112);
  app.use("/setting/getAiTokenUsageStats", route113);
  app.use("/setting/getChatHistoryDetail", route114);
  app.use("/setting/getChatHistoryList", route115);
  app.use("/setting/getLog", route116);
  app.use("/setting/getSetting", route117);
  app.use("/setting/getVideoModelDetail", route118);
  app.use("/setting/getVideoModelList", route119);
  app.use("/setting/getVoiceModelList", route120);
  app.use("/setting/localAvatarMatting", route121);
  app.use("/setting/saveStoryRuntimeConfig", route122);
  app.use("/setting/updateModel", route123);
  app.use("/setting/updeteModel", route124);
  app.use("/storyboard/batchSuperScoreImage", route125);
  app.use("/storyboard/chatStoryboard", route126);
  app.use("/storyboard/delStoryboard", route127);
  app.use("/storyboard/generateShotImage", route128);
  app.use("/storyboard/generateStoryboardApi", route129);
  app.use("/storyboard/generateVideoPrompt", route130);
  app.use("/storyboard/getStoryboard", route131);
  app.use("/storyboard/keepStoryboard", route132);
  app.use("/storyboard/saveStoryboard", route133);
  app.use("/storyboard/uploadImage", route134);
  app.use("/task/getTaskApi", route135);
  app.use("/task/taskDetails", route136);
  app.use("/user/changePassword", route137);
  app.use("/user/getUser", route138);
  app.use("/user/saveUser", route139);
  app.use("/video/addVideo", route140);
  app.use("/video/addVideoConfig", route141);
  app.use("/video/deleteVideoConfig", route142);
  app.use("/video/generateByConfig", route143);
  app.use("/video/generatePrompt", route144);
  app.use("/video/generateVideo", route145);
  app.use("/video/getManufacturer", route146);
  app.use("/video/getVideo", route147);
  app.use("/video/getVideoConfigs", route148);
  app.use("/video/getVideoModel", route149);
  app.use("/video/getVideoStoryboards", route150);
  app.use("/video/refreshVideoStatus", route151);
  app.use("/video/reviseVideoStoryboards", route152);
  app.use("/video/saveVideo", route153);
  app.use("/video/upDateVideoConfig", route154);
  app.use("/video/uploadAudio", route155);
  app.use("/voice/audioProxy", route156);
  app.use("/voice/generateBindingVoice", route157);
  app.use("/voice/getVoices", route158);
  app.use("/voice/listAliyunPresets", route159);
  app.use("/voice/listMiniMaxPresets", route160);
  app.use("/voice/mossTtsInstall", route161);
  app.use("/voice/polishPrompt", route162);
  app.use("/voice/preview", route163);
  app.use("/voice/transcribe", route164);
  app.use("/voice/uploadAudio", route165);
}
