// @routes-hash a4dbc53d42a7613aae599c04f229686a
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/delAssets";
import route3 from "./routes/assets/delAssetsImage";
import route4 from "./routes/assets/generateAssets";
import route5 from "./routes/assets/getAssets";
import route6 from "./routes/assets/getImage";
import route7 from "./routes/assets/getStoryboard";
import route8 from "./routes/assets/polishPrompt";
import route9 from "./routes/assets/saveAssets";
import route10 from "./routes/assets/updateAssets";
import route11 from "./routes/game/addMessage";
import route12 from "./routes/game/commitNarrativeTurn";
import route13 from "./routes/game/continueSession";
import route14 from "./routes/game/convertAvatarVideoToGif";
import route15 from "./routes/game/copyWorld";
import route16 from "./routes/game/debugRuntimeShared";
import route17 from "./routes/game/debugStep";
import route18 from "./routes/game/deleteChapter";
import route19 from "./routes/game/deleteMessage";
import route20 from "./routes/game/deleteSession";
import route21 from "./routes/game/deleteWorld";
import route22 from "./routes/game/generateImage";
import route23 from "./routes/game/getChapter";
import route24 from "./routes/game/getMessage";
import route25 from "./routes/game/getSession";
import route26 from "./routes/game/getTask";
import route27 from "./routes/game/getTrigger";
import route28 from "./routes/game/getWorld";
import route29 from "./routes/game/importWorldRole";
import route30 from "./routes/game/initChapter";
import route31 from "./routes/game/initDebug";
import route32 from "./routes/game/initStory";
import route33 from "./routes/game/introduction";
import route34 from "./routes/game/listImportableRoles";
import route35 from "./routes/game/listSession";
import route36 from "./routes/game/listWorlds";
import route37 from "./routes/game/orchestration";
import route39 from "./routes/game/previewRuntimeOutline";
import route40 from "./routes/game/revisitMessage";
import route41 from "./routes/game/saveChapter";
import route42 from "./routes/game/saveTask";
import route43 from "./routes/game/saveTrigger";
import route44 from "./routes/game/saveWorld";
import route45 from "./routes/game/separateRoleAvatar";
import route46 from "./routes/game/startSession";
import route47 from "./routes/game/storyInfo";
import route48 from "./routes/game/streamIntroduction";
import route49 from "./routes/game/streamlines";
import route50 from "./routes/game/streamvoice";
import route51 from "./routes/game/uploadImage";
import route52 from "./routes/index/index";
import route53 from "./routes/novel/addNovel";
import route54 from "./routes/novel/delNovel";
import route55 from "./routes/novel/getNovel";
import route56 from "./routes/novel/updateNovel";
import route57 from "./routes/other/clearDatabase";
import route58 from "./routes/other/deleteAllData";
import route59 from "./routes/other/getCaptcha";
import route60 from "./routes/other/login";
import route61 from "./routes/other/register";
import route62 from "./routes/other/testAI";
import route63 from "./routes/other/testImage";
import route64 from "./routes/other/testVideo";
import route65 from "./routes/other/testVoiceDesign";
import route66 from "./routes/outline/addOutline";
import route67 from "./routes/outline/agentsOutline";
import route68 from "./routes/outline/delOutline";
import route69 from "./routes/outline/getHistory";
import route70 from "./routes/outline/getOutline";
import route71 from "./routes/outline/getPartScript";
import route72 from "./routes/outline/getStoryline";
import route73 from "./routes/outline/setHistory";
import route74 from "./routes/outline/updateOutline";
import route75 from "./routes/outline/updateScript";
import route76 from "./routes/outline/updateStoryline";
import route77 from "./routes/project/addProject";
import route78 from "./routes/project/delProject";
import route79 from "./routes/project/getProject";
import route80 from "./routes/project/getProjectCount";
import route81 from "./routes/project/getSingleProject";
import route82 from "./routes/project/updateProject";
import route83 from "./routes/prompt/getPrompts";
import route84 from "./routes/prompt/updatePrompt";
import route85 from "./routes/script/deleteScriptSegment";
import route86 from "./routes/script/generateScriptApi";
import route87 from "./routes/script/generateScriptSave";
import route88 from "./routes/script/generateScriptSegments";
import route89 from "./routes/script/geScriptApi";
import route90 from "./routes/script/getScriptSegments";
import route91 from "./routes/script/updateScriptSegment";
import route92 from "./routes/setting/addModel";
import route93 from "./routes/setting/configurationModel";
import route94 from "./routes/setting/deleteChatHistory";
import route95 from "./routes/setting/delModel";
import route96 from "./routes/setting/getAiModelList";
import route97 from "./routes/setting/getAiModelMap";
import route98 from "./routes/setting/getAiTokenUsageLog";
import route99 from "./routes/setting/getAiTokenUsageStats";
import route100 from "./routes/setting/getChatHistoryDetail";
import route101 from "./routes/setting/getChatHistoryList";
import route102 from "./routes/setting/getLog";
import route103 from "./routes/setting/getSetting";
import route104 from "./routes/setting/getVideoModelDetail";
import route105 from "./routes/setting/getVideoModelList";
import route106 from "./routes/setting/getVoiceModelList";
import route107 from "./routes/setting/localAvatarMatting";
import route108 from "./routes/setting/saveStoryRuntimeConfig";
import route109 from "./routes/setting/updateModel";
import route110 from "./routes/setting/updeteModel";
import route111 from "./routes/storyboard/batchSuperScoreImage";
import route112 from "./routes/storyboard/chatStoryboard";
import route113 from "./routes/storyboard/delStoryboard";
import route114 from "./routes/storyboard/generateShotImage";
import route115 from "./routes/storyboard/generateStoryboardApi";
import route116 from "./routes/storyboard/generateVideoPrompt";
import route117 from "./routes/storyboard/getStoryboard";
import route118 from "./routes/storyboard/keepStoryboard";
import route119 from "./routes/storyboard/saveStoryboard";
import route120 from "./routes/storyboard/uploadImage";
import route121 from "./routes/task/getTaskApi";
import route122 from "./routes/task/taskDetails";
import route123 from "./routes/user/changePassword";
import route124 from "./routes/user/getUser";
import route125 from "./routes/user/saveUser";
import route126 from "./routes/video/addVideo";
import route127 from "./routes/video/addVideoConfig";
import route128 from "./routes/video/deleteVideoConfig";
import route129 from "./routes/video/generateByConfig";
import route130 from "./routes/video/generatePrompt";
import route131 from "./routes/video/generateVideo";
import route132 from "./routes/video/getManufacturer";
import route133 from "./routes/video/getVideo";
import route134 from "./routes/video/getVideoConfigs";
import route135 from "./routes/video/getVideoModel";
import route136 from "./routes/video/getVideoStoryboards";
import route137 from "./routes/video/refreshVideoStatus";
import route138 from "./routes/video/reviseVideoStoryboards";
import route139 from "./routes/video/saveVideo";
import route140 from "./routes/video/upDateVideoConfig";
import route141 from "./routes/video/uploadAudio";
import route142 from "./routes/voice/audioProxy";
import route143 from "./routes/voice/generateBindingVoice";
import route144 from "./routes/voice/getVoices";
import route145 from "./routes/voice/polishPrompt";
import route146 from "./routes/voice/preview";
import route147 from "./routes/voice/transcribe";
import route148 from "./routes/voice/uploadAudio";

export default async (app: Express) => {
  app.use("/assets/addAssets", route1);
  app.use("/assets/delAssets", route2);
  app.use("/assets/delAssetsImage", route3);
  app.use("/assets/generateAssets", route4);
  app.use("/assets/getAssets", route5);
  app.use("/assets/getImage", route6);
  app.use("/assets/getStoryboard", route7);
  app.use("/assets/polishPrompt", route8);
  app.use("/assets/saveAssets", route9);
  app.use("/assets/updateAssets", route10);
  app.use("/game/addMessage", route11);
  app.use("/game/commitNarrativeTurn", route12);
  app.use("/game/continueSession", route13);
  app.use("/game/convertAvatarVideoToGif", route14);
  app.use("/game/copyWorld", route15);
  app.use("/game/debugRuntimeShared", route16);
  app.use("/game/debugStep", route17);
  app.use("/game/deleteChapter", route18);
  app.use("/game/deleteMessage", route19);
  app.use("/game/deleteSession", route20);
  app.use("/game/deleteWorld", route21);
  app.use("/game/generateImage", route22);
  app.use("/game/getChapter", route23);
  app.use("/game/getMessage", route24);
  app.use("/game/getSession", route25);
  app.use("/game/getTask", route26);
  app.use("/game/getTrigger", route27);
  app.use("/game/getWorld", route28);
  app.use("/game/importWorldRole", route29);
  app.use("/game/initChapter", route30);
  app.use("/game/initDebug", route31);
  app.use("/game/initStory", route32);
  app.use("/game/introduction", route33);
  app.use("/game/listImportableRoles", route34);
  app.use("/game/listSession", route35);
  app.use("/game/listWorlds", route36);
  app.use("/game/orchestration", route37);
  app.use("/game/previewRuntimeOutline", route39);
  app.use("/game/revisitMessage", route40);
  app.use("/game/saveChapter", route41);
  app.use("/game/saveTask", route42);
  app.use("/game/saveTrigger", route43);
  app.use("/game/saveWorld", route44);
  app.use("/game/separateRoleAvatar", route45);
  app.use("/game/startSession", route46);
  app.use("/game/storyInfo", route47);
  app.use("/game/streamlines/introduction", route48);
  app.use("/game/streamlines", route49);
  app.use("/game/streamvoice", route50);
  app.use("/game/uploadImage", route51);
  app.use("/index", route52);
  app.use("/novel/addNovel", route53);
  app.use("/novel/delNovel", route54);
  app.use("/novel/getNovel", route55);
  app.use("/novel/updateNovel", route56);
  app.use("/other/clearDatabase", route57);
  app.use("/other/deleteAllData", route58);
  app.use("/other/getCaptcha", route59);
  app.use("/other/login", route60);
  app.use("/other/register", route61);
  app.use("/other/testAI", route62);
  app.use("/other/testImage", route63);
  app.use("/other/testVideo", route64);
  app.use("/other/testVoiceDesign", route65);
  app.use("/outline/addOutline", route66);
  app.use("/outline/agentsOutline", route67);
  app.use("/outline/delOutline", route68);
  app.use("/outline/getHistory", route69);
  app.use("/outline/getOutline", route70);
  app.use("/outline/getPartScript", route71);
  app.use("/outline/getStoryline", route72);
  app.use("/outline/setHistory", route73);
  app.use("/outline/updateOutline", route74);
  app.use("/outline/updateScript", route75);
  app.use("/outline/updateStoryline", route76);
  app.use("/project/addProject", route77);
  app.use("/project/delProject", route78);
  app.use("/project/getProject", route79);
  app.use("/project/getProjectCount", route80);
  app.use("/project/getSingleProject", route81);
  app.use("/project/updateProject", route82);
  app.use("/prompt/getPrompts", route83);
  app.use("/prompt/updatePrompt", route84);
  app.use("/script/deleteScriptSegment", route85);
  app.use("/script/generateScriptApi", route86);
  app.use("/script/generateScriptSave", route87);
  app.use("/script/generateScriptSegments", route88);
  app.use("/script/geScriptApi", route89);
  app.use("/script/getScriptSegments", route90);
  app.use("/script/updateScriptSegment", route91);
  app.use("/setting/addModel", route92);
  app.use("/setting/configurationModel", route93);
  app.use("/setting/deleteChatHistory", route94);
  app.use("/setting/delModel", route95);
  app.use("/setting/getAiModelList", route96);
  app.use("/setting/getAiModelMap", route97);
  app.use("/setting/getAiTokenUsageLog", route98);
  app.use("/setting/getAiTokenUsageStats", route99);
  app.use("/setting/getChatHistoryDetail", route100);
  app.use("/setting/getChatHistoryList", route101);
  app.use("/setting/getLog", route102);
  app.use("/setting/getSetting", route103);
  app.use("/setting/getVideoModelDetail", route104);
  app.use("/setting/getVideoModelList", route105);
  app.use("/setting/getVoiceModelList", route106);
  app.use("/setting/localAvatarMatting", route107);
  app.use("/setting/saveStoryRuntimeConfig", route108);
  app.use("/setting/updateModel", route109);
  app.use("/setting/updeteModel", route110);
  app.use("/storyboard/batchSuperScoreImage", route111);
  app.use("/storyboard/chatStoryboard", route112);
  app.use("/storyboard/delStoryboard", route113);
  app.use("/storyboard/generateShotImage", route114);
  app.use("/storyboard/generateStoryboardApi", route115);
  app.use("/storyboard/generateVideoPrompt", route116);
  app.use("/storyboard/getStoryboard", route117);
  app.use("/storyboard/keepStoryboard", route118);
  app.use("/storyboard/saveStoryboard", route119);
  app.use("/storyboard/uploadImage", route120);
  app.use("/task/getTaskApi", route121);
  app.use("/task/taskDetails", route122);
  app.use("/user/changePassword", route123);
  app.use("/user/getUser", route124);
  app.use("/user/saveUser", route125);
  app.use("/video/addVideo", route126);
  app.use("/video/addVideoConfig", route127);
  app.use("/video/deleteVideoConfig", route128);
  app.use("/video/generateByConfig", route129);
  app.use("/video/generatePrompt", route130);
  app.use("/video/generateVideo", route131);
  app.use("/video/getManufacturer", route132);
  app.use("/video/getVideo", route133);
  app.use("/video/getVideoConfigs", route134);
  app.use("/video/getVideoModel", route135);
  app.use("/video/getVideoStoryboards", route136);
  app.use("/video/refreshVideoStatus", route137);
  app.use("/video/reviseVideoStoryboards", route138);
  app.use("/video/saveVideo", route139);
  app.use("/video/upDateVideoConfig", route140);
  app.use("/video/uploadAudio", route141);
  app.use("/voice/audioProxy", route142);
  app.use("/voice/generateBindingVoice", route143);
  app.use("/voice/getVoices", route144);
  app.use("/voice/polishPrompt", route145);
  app.use("/voice/preview", route146);
  app.use("/voice/transcribe", route147);
  app.use("/voice/uploadAudio", route148);
}
